---
version: "3"
services:
 devopsdb:
   image: rohini27/project2:dbimage
   ports:
     - "3306:3306"

 application:
   image: rohini27/project2:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
